# Generated by Django 4.2.18 on 2025-02-10 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leopardscoffee.custom_field
import leopardscoffee.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có từ 9 đến 15 chữ số và có thể bắt đầu bằng dấu '+'.", regex='^\\+?1?\\d{9,15}$')])),
                ('image', models.ImageField(upload_to=leopardscoffee.helpers.get_user_image_path)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopardscoffee.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('isValid', leopardscoffee.custom_field.CustomBooleanField()),
                ('image', models.ImageField(upload_to=leopardscoffee.helpers.get_product_image_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopardscoffee.categories')),
            ],
        ),
    ]
