# Generated by Django 4.2.18 on 2025-02-10 12:56

from django.db import migrations, models
import django.db.models.deletion
import leopardscoffee.custom_field
import leopardscoffee.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('leopardscoffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('isValid', leopardscoffee.custom_field.CustomBooleanField()),
                ('image', models.ImageField(upload_to=leopardscoffee.helpers.get_file_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopardscoffee.categories')),
            ],
        ),
    ]
