# Generated by Django 4.2.18 on 2025-02-11 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leopardscoffee.custom_field
import leopardscoffee.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('leopardscoffee', '0002_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('isActive', leopardscoffee.custom_field.CustomBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TableDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có từ 9 đến 15 chữ số và có thể bắt đầu bằng dấu '+'.", regex='^\\+?1?\\d{9,15}$')])),
                ('image', models.ImageField(upload_to=leopardscoffee.helpers.get_user_image_path)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Dish',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leopardscoffee.role'),
        ),
        migrations.AddField(
            model_name='tabledish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leopardscoffee.dish'),
        ),
        migrations.AddField(
            model_name='tabledish',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_dishes', to='leopardscoffee.table'),
        ),
    ]
