# Generated by Django 4.2.18 on 2025-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leopardscoffee', '0004_bill_cart_cartitem_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
    ]
